### ISSUE TITLE
bug: mismatch in base64Encode results between crypto-js

### ISSUE THREAD

**Issue by Hanna922** [yourssu/Yrano#32]
# ISSUE ✅ : mismatch in base64Encode results between crypto-js

## 📖 Summary

sha256 결과를 바탕으로 base64Encode를 돌릴 경우 crypto-js와 값이 다르게 나옵니다.

## Fail Test Code (base64Encode.test.ts)

```ts
  it('should encode an empty sha256 hash value to base64', () => {
    expect(base64Encode(sha256(''))).toBe(
      CryptoJS.enc.Base64.stringify(CryptoJS.SHA256('')).toString()
    );
  });

  it('should encode a sha256 hash value to base64', () => {
    expect(base64Encode('9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')).toBe(
      CryptoJS.enc.Base64.stringify(
        CryptoJS.SHA256('9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')
      ).toString()
    );
  });
```

## Photo

4번 로그(crypto-js 사용)가 올바른 값이며, 8번 로그(@yourssu/crypto 사용)가 잘못된 값입니다.

<img width="971" alt="image" src="https://github.com/yourssu/Yrano/assets/84809236/f8edcf11-6981-4f34-ac3e-c6babdbe80d8">

sha256의 경우 값이 일치하며, base64Encode 시 문제가 생기는 것을 확인하였습니다.

<img width="956" alt="image" src="https://github.com/yourssu/Yrano/assets/84809236/624ac794-2d0b-437c-93bc-d50e80ab575f">

## 재현 방법

apps/demo 에서 하단 코드 삽입

```tsx
import { base64Encode, sha256 } from '@yourssu/crypto';
import CryptoJS from 'crypto-js';

export const Home = () => {
  ...
  console.log(sha256('test'), 'sha256 test - @yourssu/crypto');
  console.log(CryptoJS.SHA256('test').toString(), 'sha256 test - CryptoJS');
  console.log(base64Encode(sha256('test')), 'base64Encode test - @yourssu/crypto');
  console.log(
    CryptoJS.SHA256('test').toString(CryptoJS.enc.Base64),
    'base64Encode test - CryptoJS'
  );
```

**Comment by owl1753** [comment]
테스트 코드에서 ```'9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08'```은 이미 sha256이 적용된 상태인데 거기다가 ```CryptoJS.SHA256``` 함수를 한 번 더 적용해서 값이 다르게 나온 것 같네요.
```ts
it('should encode a sha256 hash value to base64', () => {
  expect(base64Encode('9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')).toBe(
    CryptoJS.enc.Base64.stringify(
      CryptoJS.enc.Utf8.parse('9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08')
    ).toString()
  );
});
```
이 경우에는 테스트를 통과합니다.

추가적으로 찾아보니

@yourssu/crypto에서는 utf-8 문자 => sha256 해싱 적용 => hex 문자열 =>  utf-8 변환 => base64인코딩
crypto-js에서는 utf-8 문자 => sha256 해싱 적용 => hex 문자열 => base64인코딩

이런 식으로 @yourssu/crypto에서 hex 문자열을 utf-8 로 변환하는 과정이 섞여있어서 값이 다르게 나오는 것 같습니다.
